version: '3.8'

services:

  db:
    image: postgres
    restart: always
    ports:
      - 5555:5432
    environment:
      POSTGRES_DB: store_db
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password